LocadoraDeVeiculos.WebApp/Models/CondutorViewModels.cs
using AutoMapper.Configuration.Annotations;
using LocadoraDeVeiculos.Dominio;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace LocadoraDeVeiculos.WebApp.Models;

public class FormCondutorViewModel
{
    public int Id { get; set; }

    [Required(ErrorMessage = "A CNH é obrigatória.")]
    [StringLength(11, ErrorMessage = "A CNH deve ter 11 caracteres.")]
    public string CNH { get; set; }

    [Required(ErrorMessage = "A validade da CNH é obrigatória.")]
    [DataType(DataType.Date)]
    [Display(Name = "Validade da CNH")]
    public DateTime ValidadeCNH { get; set; }

    [Required(ErrorMessage = "O cliente é obrigatório.")]
    public int ClienteId { get; set; }

    [Ignore]
    public Cliente Cliente { get; set; }

    [Ignore]
    public IEnumerable<SelectListItem> Clientes { get; set; }

    [Display(Name = "Cliente é condutor")]
    public bool ClienteCondutor { get; set; }

    [Required(ErrorMessage = "O nome é obrigatório.")]
    [StringLength(100, ErrorMessage = "O nome deve ter no máximo 100 caracteres.")]
    public string? Nome { get; set; }

    [EmailAddress(ErrorMessage = "Endereço de e-mail inválido.")]
    [StringLength(100, ErrorMessage = "O e-mail deve ter no máximo 100 caracteres.")]
    public string? Email { get; set; }

    [Required(ErrorMessage = "O telefone é obrigatório.")]
    [StringLength(16, ErrorMessage = "O telefone deve ter no máximo 11 caracteres.")]
    public string? Telefone { get; set; }

    [Required(ErrorMessage = "O CPF é obrigatório.")]
    [MinLength(14, ErrorMessage = "O CPF deve conter 11 dígitos.")]
    public string? CPF { get; set; }
}

public class ListarCondutorViewModel : FormCondutorViewModel
{
    public Cliente Cliente { get; set; }

    public string DefinirCondutor(string NomeCondutor, Cliente cliente)
    {
        if (NomeCondutor != cliente.Nome)
            return cliente.Nome;

        return "O cliente é o Condutor";
    }

    public string CpfOuCnpj(Cliente cliente)
    {
        if (cliente.CNPJ != null)
            return cliente.CNPJ;

        return cliente.CPF;
    }
}

LocadoraDeVeiculos.WebApp/Controllers/CondutorController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using LocadoraDeVeiculos.Dominio;
using LocadoraDeVeiculos.WebApp.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using LocadoraDeVeiculos.Aplicacao.Services;
using LocadoraDeVeiculos.WebApp.Extensions;
using LocadoraDeVeiculos.WebApp.Controllers.Shared;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace LocadoraDeVeiculos.WebApp.Controllers;
public class CondutorController : WebController
{
    readonly IMapper _mapeador;
    readonly ClienteService _serviceCliente;
    readonly CondutorService _serviceCondutor;

    public CondutorController(IMapper mapeador, ClienteService serviceCliente, CondutorService condutorService, AuthService authService) : base(authService)
    {
        _mapeador = mapeador;
        _serviceCliente = serviceCliente;
        _serviceCondutor = condutorService;
    }

    public IActionResult Listar()
    {
        var resultado = _serviceCondutor.SelecionarTodos(EmpresaId.GetValueOrDefault());

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction("Index", "Home");
        }

        var condutores = resultado.Value;

        var listarVM = _mapeador.Map<IEnumerable<ListarCondutorViewModel>>(condutores);

        ViewBag.Mensagem = TempData.DesserializarMensagemViewModel();

        return View(listarVM);
    }

    public IActionResult Detalhes(int id)
    {
        var resultado = _serviceCondutor.SelecionarId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var condutor = resultado.Value;

        var detalhesVM = _mapeador.Map<FormCondutorViewModel>(condutor);

        return View(detalhesVM);
    }

    public IActionResult Cadastrar()
    {
        return View(CarregarDadosFormulario());
    }

    [HttpPost]
    public IActionResult Cadastrar(FormCondutorViewModel cadastroVm)
    {
        ModelState.Remove("Cliente");
        ModelState.Remove("Clientes");

        if (!ModelState.IsValid)
            return View(CarregarDadosFormulario(cadastroVm));

        var condutor = _mapeador.Map<Condutor>(cadastroVm);

        var resultado = _serviceCondutor.Cadastrar(condutor);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"O registro ID [{condutor.Id}] foi cadastrado com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    [HttpGet]
    public JsonResult CarregarDadosCondutores(int clienteId)
    {
        var resultado = _serviceCliente.SelecionarId(clienteId);

        if (resultado.IsFailed)
        {
            return Json(new { success = false, message = "Cliente não encontrado." });
        }

        var cliente = resultado.Value;

        var dadosCliente = new
        {
            Nome = cliente.Nome,
            CPF = cliente.CPF,
            Telefone = cliente.Telefone,
            Email = cliente.Email,
            CNPJ = cliente.CNPJ
        };

        return Json(new { success = true, dados = dadosCliente });
    }


    public IActionResult Editar(int id)
    {
        var resultado = _serviceCondutor.SelecionarId(id);
        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var clientes = _serviceCliente.SelecionarTodos(EmpresaId.GetValueOrDefault());

        if (clientes.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return null;
        }

        var condutor = resultado.Value;

        var editarVm = _mapeador.Map<FormCondutorViewModel>(condutor);

        var clientesElegiveis = clientes.Value;

        editarVm.Clientes = clientesElegiveis
            .Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Nome,
                Selected = c.Id == condutor.Id
            });

        return View(editarVm);
    }

    [HttpPost]
    public IActionResult Editar(FormCondutorViewModel editarVm)
    {
        ModelState.Remove("Cliente");
        ModelState.Remove("Clientes");

        if (!ModelState.IsValid)
            return View(editarVm);

        var condutor = _mapeador.Map<Condutor>(editarVm);

        var resultado = _serviceCondutor.Editar(condutor);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Editar));
        }

        ApresentarMensagemSucesso($"O registro ID [{condutor.Id}] foi editado com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    public IActionResult Excluir(int id)
    {
        var resultado = _serviceCondutor.SelecionarId(id);
        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());
            return RedirectToAction(nameof(Listar));
        }

        var condutor = resultado.Value;

        var excluirVm = _mapeador.Map<FormCondutorViewModel>(condutor);

        return View(excluirVm);
    }

    [HttpPost]
    public IActionResult Excluir(FormCondutorViewModel excluirVm)
    {
        var resultado = _serviceCondutor.Excluir(excluirVm.Id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }


        ApresentarMensagemSucesso($"O registro foi deletado com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    private FormCondutorViewModel? CarregarDadosFormulario(
      FormCondutorViewModel? dadosPrevios = null)
    {
        var resultadoClientes = _serviceCliente.SelecionarTodos(EmpresaId.GetValueOrDefault());

        if (resultadoClientes.IsFailed)
        {
            ApresentarMensagemFalha(resultadoClientes.ToResult());
            return null;
        }

        var Disponiveis = resultadoClientes.Value;

        if (dadosPrevios is null)
        {
            var formularioVm = new FormCondutorViewModel
            {
                Clientes = Disponiveis.Select(c => new SelectListItem(c.Nome, c.Id.ToString()))
            };
            return formularioVm;
        }

        dadosPrevios.Clientes = Disponiveis.Select(c => new SelectListItem(c.Nome, c.Id.ToString()));
        return dadosPrevios;
    }
}

LocadoraDeVeiculos.WebApp/Views/Condutor/Cadastrar.cshtml
@model FormCondutorViewModel

@{
    ViewBag.Title = "Cadastro de Condutor";
}

@* //Perguntar sobre como colocar o valor dos atributos no input *@
<hr />
<div class="row d-flex justify-content-center">
    <div class="col-lg-6 ">
        <form asp-action="Cadastrar" method="post">
            <div class="form-group">
                <label for="ClienteId">Cliente:</label>
                <select asp-for="ClienteId" class="form-control" asp-items="Model.Clientes" id="clienteSelect"></select>
            </div>

            <div class="form-group">
                <input asp-for="ClienteCondutor" value="true" type="checkbox" id="ClienteCondutor" />
                <label for="ClienteCondutor">Cliente é condutor</label>
            </div>

            <div class="form-group">
                <label asp-for="Nome" class="control-label">Nome:</label>
                <input asp-for="Nome" id="nome" class="form-control" required />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="control-label">Email:</label>
                <input asp-for="Email" id="email" class="form-control" required />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Telefone" class="control-label">Telefone:</label>
                <input asp-for="Telefone" id="fone" maxlength="16" class="form-control" required />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CPF" class="control-label">CPF/CNPJ:</label>
                <input asp-for="CPF" id="cpf" maxlength="14" class="form-control" required />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CNH" class="control-label">CNH:</label>
                <input asp-for="CNH" maxlength="11" class="form-control" required />
                <span asp-validation-for="CNH" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ValidadeCNH" class="control-label">Validade:</label>
                <input asp-for="ValidadeCNH" class="form-control" type="date" value="2000-01-01" />
                <span asp-validation-for="ValidadeCNH" class="text-danger"></span>
            </div>

            <div class="form-group my-3">
                <button type="submit" class="btn btn-primary">Cadastrar</button>
                <a asp-action="Listar" class="btn btn-secondary">Cancelar</a>
            </div>
        </form>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var cpfInput = document.getElementById('cpf');
        var telefoneInput = document.getElementById('fone');
        var emailInput = document.getElementById('email');
        var nomeInput = document.getElementById('nome');
        var clienteCondutorCheckbox = document.getElementById('ClienteCondutor');
        var clienteSelect = document.getElementById('clienteSelect');

        function atualizarCamposCondutor() {
            var ehCondutor = clienteCondutorCheckbox.checked;
            var clienteId = clienteSelect.value;

            cpfInput.readOnly = ehCondutor;
            telefoneInput.readOnly = ehCondutor;
            emailInput.readOnly = ehCondutor;
            nomeInput.readOnly = ehCondutor;

            if (ehCondutor && clienteId) {
                $.get('@Url.Action("CarregarDadosCondutores", "Condutor")', { clienteId: clienteId }, function (Resposta) {
                    console.log(Resposta);
                    if (Resposta.success) {
                        var cliente = Resposta.dados;
                        nomeInput.value = cliente.nome;
                        telefoneInput.value = cliente.telefone;
                        emailInput.value = cliente.email;
                        if (ehCondutor && cliente.cpf === null) {
                            cpfInput.value = cliente.cnpj;
                        } else {

                            cpfInput.value = cliente.cpf;
                        }
                    }
                });
            } else {
                nomeInput.value = '';
                cpfInput.value = '';
                telefoneInput.value = '';
                emailInput.value = '';
            }
        }

        clienteCondutorCheckbox.addEventListener('change', atualizarCamposCondutor);
        clienteSelect.addEventListener('change', atualizarCamposCondutor);

        atualizarCamposCondutor();


        cpfInput.addEventListener('input', function () {
            var value = cpfInput.value.replace(/\D/g, '');
            if (value.length <= 11) {
                value = value.replace(/(\d{3})(\d)/, '$1.$2');
                value = value.replace(/(\d{3})(\d)/, '$1.$2');
                value = value.replace(/(\d{3})(\d{1,2})$/, '$1-$2');
                cpfInput.value = value;
            }
        });

        telefoneInput.addEventListener('input', function () {
            var value = telefoneInput.value.replace(/\D/g, '');
            if (value.length <= 11) {
                value = value.replace(/(\d{2})(\d)/, '($1) $2');
                value = value.replace(/(\d{1})(\d{4})(\d{4})$/, '$1 $2-$3');
                telefoneInput.value = value;
            }
        });
    });
</script>

LocadoraDeVeiculos.WebApp/Views/Condutor/Detalhes.cshtml
@model FormCondutorViewModel

@{
    ViewBag.Title = "Excluir Condutor";
}

<hr />
<div class="row d-flex justify-content-center">
    <div class="col-lg-6 ">
        <div class="alert alert-danger" role="alert">
            <strong>Tem certeza que deseja excluir este condutor?</strong>
        </div>

        <div class="form-group">
            <label>Nome:</label>
            <input class="form-control" value="@Model.Nome" disabled />
        </div>

        <div class="form-group">
            <label>Email:</label>
            <input class="form-control" value="@Model.Email" disabled />
        </div>

        <div class="form-group">
            <label>Telefone:</label>
            <input class="form-control" value="@Model.Telefone" disabled />
        </div>

        <div class="form-group">
            <label>CPF:</label>
            <input class="form-control" value="@Model.CPF" disabled />
        </div>

        <div class="form-group">
            <label>CNH:</label>
            <input class="form-control" value="@Model.CNH" disabled />
        </div>

        <div class="form-group">
            <label>Validade CNH:</label>
            <input class="form-control" value="@Model.ValidadeCNH.ToString("dd/MM/yyyy")" disabled />
        </div>

        <hr />

        <h4>Informações do Cliente</h4>

        <div class="form-group">
            <label>RG:</label>
            <input class="form-control" value="@Model.Cliente.RG" disabled />
        </div>

        <div class="form-group">
            <label>Nome do Cliente:</label>
            <input class="form-control" value="@Model.Cliente.Nome" disabled />
        </div>

        <div class="form-group">
            <label>Email do Cliente:</label>
            <input class="form-control" value="@Model.Cliente.Email" disabled />
        </div>

        <div class="form-group">
            <label>Telefone do Cliente:</label>
            <input class="form-control" value="@Model.Cliente.Telefone" disabled />
        </div>

        <div class="form-group">
            <label>Endereço do Cliente:</label>
            <input class="form-control" value="@Model.Cliente.Endereco" disabled />
        </div>

        <div class="form-group">
            <label>CPF do Cliente:</label>
            <input class="form-control" value="@Model.Cliente.CPF" disabled />
        </div>

        <div class="form-group">
            <label>CNPJ do Cliente:</label>
            <input class="form-control" value="@Model.Cliente.CNPJ" disabled />
        </div>

        <div class="form-group">
            <label>Tipo de Perfil:</label>
            <input class="form-control" value="@(Model.Cliente.TipoPerfil ? "Pessoa Física" : "Pessoa Jurídica")" disabled />
        </div>



        <a asp-action="Listar" class="btn btn-secondary my-3">Voltar</a>
    </div>
</div>

LocadoraDeVeiculos.WebApp/Views/Condutor/Editar.cshtml
@model FormCondutorViewModel

@{
    ViewBag.Title = "Edição de Condutor";
}

<hr />
<div class="row d-flex justify-content-center">
    <div class="col-lg-6 ">
        <form asp-action="Editar" method="post">
            <div class="form-group">
                <label for="ClienteId">Cliente:</label>
                <select asp-for="ClienteId" class="form-control" asp-items="Model.Clientes" id="clienteSelect"></select>
            </div>

            <div class="form-group">
                <input asp-for="ClienteCondutor" value="true" type="checkbox" id="ClienteCondutor" readonly/>
                <label for="ClienteCondutor">Cliente é condutor</label>
            </div>

            <div class="form-group">
                <label asp-for="Nome" class="control-label">Nome:</label>
                <input asp-for="Nome" id="nome" class="form-control" required />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="control-label">Email:</label>
                <input asp-for="Email" id="email" class="form-control" required />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Telefone" class="control-label">Telefone:</label>
                <input asp-for="Telefone" id="fone" maxlength="16" class="form-control" required />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CPF" class="control-label">CPF/CNPJ:</label>
                <input asp-for="CPF" id="cpf" maxlength="14" class="form-control" required />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CNH" class="control-label">CNH:</label>
                <input asp-for="CNH" maxlength="11" class="form-control" required />
                <span asp-validation-for="CNH" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ValidadeCNH" class="control-label">Validade:</label>
                <input asp-for="ValidadeCNH" class="form-control" type="date" value="2000-01-01" />
                <span asp-validation-for="ValidadeCNH" class="text-danger"></span>
            </div>

            <div class="form-group my-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
                <a asp-action="Listar" class="btn btn-secondary">Cancelar</a>
            </div>
        </form>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var cpfInput = document.getElementById('cpf');
        var telefoneInput = document.getElementById('fone');
        var emailInput = document.getElementById('email');
        var nomeInput = document.getElementById('nome');
        var clienteCondutorCheckbox = document.getElementById('ClienteCondutor');
        var clienteSelect = document.getElementById('clienteSelect');

        function atualizarCamposCondutor() {
            var ehCondutor = clienteCondutorCheckbox.checked = true;
            var clienteId = clienteSelect.value;

            cpfInput.readOnly = ehCondutor;

            if (ehCondutor && clienteId) {
                $.get('@Url.Action("CarregarDadosCondutores", "Condutor")', { clienteId: clienteId }, function (Resposta) {
                    console.log(Resposta);
                    if (Resposta.success) {
                        var cliente = Resposta.dados;
                        nomeInput.value = cliente.nome;
                        telefoneInput.value = cliente.telefone;
                        emailInput.value = cliente.email;
                        if (ehCondutor && cliente.cpf === null) {
                            cpfInput.value = cliente.cnpj;
                        } else {

                            cpfInput.value = cliente.cpf;
                        }
                    }
                });
            } else {
                nomeInput.value = '';
                cpfInput.value = '';
                telefoneInput.value = '';
                emailInput.value = '';
            }
        }

        clienteCondutorCheckbox.addEventListener('change', atualizarCamposCondutor);
        clienteSelect.addEventListener('change', atualizarCamposCondutor);

        atualizarCamposCondutor();


        cpfInput.addEventListener('input', function () {
            var value = cpfInput.value.replace(/\D/g, '');
            if (value.length <= 11) {
                value = value.replace(/(\d{3})(\d)/, '$1.$2');
                value = value.replace(/(\d{3})(\d)/, '$1.$2');
                value = value.replace(/(\d{3})(\d{1,2})$/, '$1-$2');
                cpfInput.value = value;
            }
        });

        telefoneInput.addEventListener('input', function () {
            var value = telefoneInput.value.replace(/\D/g, '');
            if (value.length <= 11) {
                value = value.replace(/(\d{2})(\d)/, '($1) $2');
                value = value.replace(/(\d{1})(\d{4})(\d{4})$/, '$1 $2-$3');
                telefoneInput.value = value;
            }
        });
    });
</script>

LocadoraDeVeiculos.WebApp/Views/Condutor/Excluir.cshtml
@model FormCondutorViewModel

@{
    ViewBag.Title = "Excluir Condutor";
}

<hr />
<div class="row d-flex justify-content-center">
    <div class="col-lg-6 ">
        <div class="alert alert-danger" role="alert">
            <strong>Tem certeza que deseja excluir este condutor?</strong>
        </div>

        <div class="form-group">
            <label>Nome:</label>
            <input class="form-control" value="@Model.Nome" disabled />
        </div>

        <div class="form-group">
            <label>Email:</label>
            <input class="form-control" value="@Model.Email" disabled />
        </div>

        <div class="form-group">
            <label>Telefone:</label>
            <input class="form-control" value="@Model.Telefone" disabled />
        </div>

        <div class="form-group">
            <label>CPF:</label>
            <input class="form-control" value="@Model.CPF" disabled />
        </div>

        <div class="form-group">
            <label>CNH:</label>
            <input class="form-control" value="@Model.CNH" disabled />
        </div>

        <div class="form-group">
            <label>Validade CNH:</label>
            <input class="form-control" value="@Model.ValidadeCNH.ToString("dd/MM/yyyy")" disabled />
        </div>

        <form asp-action="Excluir" method="post">
            <input type="hidden" asp-for="Id" />
            <div class="form-group my-3">
                <button type="submit" value="Excluir" class="btn btn-danger">Excluir</button>
                <a asp-action="Listar" class="btn btn-secondary">Cancelar</a>
            </div>
        </form>
    </div>
</div>

LocadoraDeVeiculos.WebApp/Views/Condutor/Listar.cshtml
@model IEnumerable<ListarCondutorViewModel>

@{
    ViewBag.Title = "Listagem de Condutores";
}

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Condutor</th>
            <th>Cliente</th>
            <th>CPF/CNPJ</th>
            <th>CNH</th>
            <th>Validade CNH</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var condutor in Model)
        {
            <tr>
                <td>@condutor.Id</td>
                <td>@condutor.Nome</td>
                <td>@condutor.DefinirCondutor(condutor.Nome,@condutor.Cliente)</td>
                <td>@condutor.CpfOuCnpj(condutor.Cliente)</td>
                <td>@condutor.CNH</td>
                <td>@condutor.ValidadeCNH.ToString("dd/MM/yyyy")</td>
                <td>
                    <a asp-action="Editar" asp-route-id="@condutor.Id" class="btn btn-primary">Editar</a>
                    <a asp-action="Detalhes" asp-route-id="@condutor.Id" class="btn btn-info">Detalhes</a>
                    <a asp-action="Excluir" asp-route-id="@condutor.Id" class="btn btn-danger">Excluir</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<a asp-action="Cadastrar" class="btn btn-primary">Cadastrar Novo Condutor</a>