LocadoraDeVeiculos.WebApp/Models/AluguelViewModels.cs
using LocadoraDeVeiculos.Dominio;
using Microsoft.AspNetCore.Mvc.Rendering;
using LocadoraDeVeiculos.Dominio.ModuloVeiculos;
using LocadoraDeVeiculos.Dominio.ModuloAlugueis.ModuloTaxas;
using LocadoraDeVeiculos.Dominio.ModuloVeiculos.ModuloCombustiveis;
using LocadoraDeVeiculos.Dominio.ModuloVeiculos.ModuloGrupoVeiculos;

namespace LocadoraDeVeiculos.WebApp.Models;

public class FormAluguelViewModel
{
    public int Id { get; set; }
    public List<TaxaServico>? Taxas { get; set; }
    public int Entrada { get; set; } = 1000;
    public IEnumerable<SelectListItem>? Condutores { get; set; }
    public IEnumerable<SelectListItem>? Veiculos { get; set; }
    public IEnumerable<SelectListItem>? Clientes { get; set; }
    public IEnumerable<SelectListItem>? Planos { get; set; }
    public IEnumerable<SelectListItem>? Grupos { get; set; }
    public DateTime DataLocacao { get; set; } = DateTime.UtcNow;
    public DateTime? DateDevolucaoPrevista { get; set; } = DateTime.UtcNow;
    public List<int> taxasSelecionadas { get; set; } = new List<int>();

    public int PlanoId { get; set; }
    public int VeiculoId { get; set; }
    public int GrupoId { get; set; }
    public int CondutorId { get; set; }
    public int ClienteId { get; set; }
    public int SeguroId { get; set; }
    public int TaxaServicoId { get; set; }
    public int KmFinal { get; set; }

}
public class ListarAluguelViewModel : FormAluguelViewModel
{
    public string Condutor { get; set; }
    public string Veiculo { get; set; }
    public string Cliente { get; set; }
    public string Plano { get; set; }
    public string Seguro { get; set; }
    public string Grupo { get; set; }
    public bool encerrado { get; set; }
}

public class CadastroAluguelViewModel : FormAluguelViewModel
{
    public IEnumerable<SelectListItem>? Condutores { get; set; }
    public IEnumerable<SelectListItem>? Veiculos { get; set; }
    public IEnumerable<SelectListItem>? Clientes { get; set; }
    public IEnumerable<SelectListItem>? Planos { get; set; }
    public IEnumerable<SelectListItem>? Grupos { get; set; }
    public decimal? ValorFinal { get; set; } = 0;
    public EnumMarcadorCombustivel marcadorCombustivel { get; set; }

}
public class ExcluirAluguelViewModel : FormAluguelViewModel
{
    public Cliente Cliente { get; set; }
    public Condutor Condutor { get; set; }
    public Veiculo Veiculo { get; set; }
    public Plano Plano { get; set; }
    public GrupoVeiculos Grupo { get; set; }
}
public class EditarAluguelViewModel : FormAluguelViewModel
{
    public IEnumerable<SelectListItem>? Condutores { get; set; }
    public IEnumerable<SelectListItem>? Clientes { get; set; }
    public IEnumerable<SelectListItem>? Veiculos { get; set; }
    public IEnumerable<SelectListItem>? Planos { get; set; }
    public IEnumerable<SelectListItem>? Grupos { get; set; }
    public decimal? ValorFinal { get; set; } = 0;
    public List<int> taxasSelecionadas { get; set; } = new List<int>();
}
public class FinalizarAluguelViewModel : FormAluguelViewModel
{
    public List<TaxaServico> Taxas { get; set; }
    public List<int> TaxasId { get; set; }
    public decimal? ValorFinal { get; set; }
    public int KmFinal { get; set; }
    public Cliente Cliente { get; set; }
    public Condutor Condutor { get; set; }
    public Combustivel Combustivel { get; set; }
    public Veiculo Veiculo { get; set; }
    public Aluguel Aluguel { get; set; }
    public Plano Plano { get; set; }
    public GrupoVeiculos Grupo { get; set; }
}
public class DetalhesAluguelViewModel : FormAluguelViewModel
{
    public Cliente Cliente { get; set; }
    public Condutor Condutor { get; set; }
    public Veiculo Veiculo { get; set; }
    public Plano Plano { get; set; }
    public GrupoVeiculos Grupo { get; set; }
    public List<TaxaServico> Taxas { get; set; }
}

public class PrefinalizarAluguelViewModel : CadastroAluguelViewModel
{
    public int KmFinal { set; get; }
    public decimal? ValorFinal { set; get; }
    public Aluguel Aluguel { get; set; }
    public Combustivel Combustivel { get; set; }
    public EnumMarcadorCombustivel QuantiaCombustivel { get; set; }
}

LocadoraDeVeiculos.WebApp/Controllers/AluguelController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using LocadoraDeVeiculos.Dominio;
using LocadoraDeVeiculos.WebApp.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using LocadoraDeVeiculos.WebApp.Extensions;
using LocadoraDeVeiculos.Aplicacao.Services;
using LocadoraDeVeiculos.WebApp.Controllers.Shared;
using LocadoraDeVeiculos.Dominio.ModuloVeiculos.ModuloCombustiveis;
using Microsoft.SqlServer.Server;

namespace LocadoraDeVeiculos.WebApp.Controllers;
public class AluguelController : WebController
{
    readonly IMapper _mapeador;
    readonly PlanoService _planoService;
    readonly TaxasService _taxasService;
    readonly VeiculoService _veiculoService;
    readonly AluguelService _aluguelService;
    readonly ClienteService _clienteService;
    readonly CondutorService _condutorService;
    readonly GrupoVeiculosService _grupoVeiculosService;

    public AluguelController(
        IMapper mapeador,
        AuthService authService,
        PlanoService planoService,
        TaxasService taxasService,
        VeiculoService veiculoService,
        AluguelService aluguelService,
        ClienteService clienteService,
        CondutorService condutorService,
        GrupoVeiculosService grupoVeiculosService) : base(authService)
    {
        _mapeador = mapeador;
        _planoService = planoService;
        _taxasService = taxasService;
        _veiculoService = veiculoService;
        _aluguelService = aluguelService;
        _clienteService = clienteService;
        _condutorService = condutorService;
        _grupoVeiculosService = grupoVeiculosService;
    }

    public IActionResult Listar()
    {
        var resultado = _aluguelService.SelecionarTodos();

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult()); ////Ainda não implementado

            return View("Index", "Home");
        }
        var alugueis = resultado.Value;

        var listarVM = _mapeador.Map<IEnumerable<ListarAluguelViewModel>>(alugueis);

        ViewBag.Mensagem = TempData.DesserializarMensagemViewModel();

        return View(listarVM);
    }

    public IActionResult Detalhes(int id)
    {
        var resultado = _aluguelService.SelecionarId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var aluguel = resultado.Value;

        var detalhesVm = _mapeador.Map<DetalhesAluguelViewModel>(aluguel);

        return View(detalhesVm);
    }

    public IActionResult Cadastrar()
    {
        return View(CarregarDados());
    }

    [HttpPost]
    public IActionResult Cadastrar(CadastroAluguelViewModel cadastroVm)
    {
        if (!ModelState.IsValid)
            return View(CarregarDados(cadastroVm));


        var aluguel = _mapeador.Map<Aluguel>(cadastroVm);

        foreach (var taxaId in cadastroVm.taxasSelecionadas)
        {
            var result = _taxasService.SelecionarId(taxaId);

            var taxa = result.Value;

            if (aluguel.Taxas.Find(c => c.Id == taxaId) == null && taxa != null)
                aluguel.Taxas.Add(taxa);
        }

        var resultado = _aluguelService.Cadastrar(aluguel);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"O registro ID [{aluguel.Id}] foi cadastrado com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    public IActionResult PreFinalizacao(int id)
    {
        var resultado = _aluguelService.SelecionarId(id);

        var aluguel = resultado.Value;

        var resultadoTaxas = _taxasService.SelecionarTodos(EmpresaId.GetValueOrDefault());

        if (resultadoTaxas.IsFailed)
        {
            ApresentarMensagemFalha(resultadoTaxas.ToResult());
            return null;
        }
        var taxas = resultadoTaxas.Value;

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var preFinalizarVm = _mapeador.Map<PrefinalizarAluguelViewModel>(aluguel);

        preFinalizarVm.Taxas = taxas;

        return View(preFinalizarVm);
    }

    [HttpPost]
    public IActionResult CalcularValorFinal(PrefinalizarAluguelViewModel preFinalizacaoVm)
    {
        var resultado = _aluguelService.SelecionarId(preFinalizacaoVm.Id);

        var aluguel = resultado.Value;

        foreach (var taxaId in preFinalizacaoVm.taxasSelecionadas)
        {
            var result = _taxasService.SelecionarId(taxaId);

            var taxa = result.Value;

            if (aluguel.Taxas.Find(c => c.Id == taxaId) == null && taxa != null)
                aluguel.Taxas.Add(taxa);
        }

        _aluguelService.Salvar(aluguel);

        aluguel.marcadorCombustivel = preFinalizacaoVm.QuantiaCombustivel;

        int? distancia = _aluguelService.QuilometrosPercorrido(aluguel, preFinalizacaoVm.KmFinal);

        preFinalizacaoVm.ValorFinal = aluguel.CalcularValorParcial(distancia);

        return RedirectToAction(nameof(Finalizar), preFinalizacaoVm);
    }

    public IActionResult Finalizar(int id, int KmFinal, decimal valorFinal)
    {
        var resultado = _aluguelService.SelecionarId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var aluguel = resultado.Value;

        aluguel.KmFinal = KmFinal;

        _aluguelService.Salvar(aluguel);

        var finalizarVm = _mapeador.Map<FinalizarAluguelViewModel>(aluguel);

        finalizarVm.ValorFinal = valorFinal;

        return View(finalizarVm);
    }

    [HttpPost]
    public IActionResult Finalizar(FinalizarAluguelViewModel finalizarAluguel)
    {
        var resultado = _aluguelService.SelecionarId(finalizarAluguel.Id);

        var aluguel = resultado.Value;

        _aluguelService.Finalizar(aluguel);

        ApresentarMensagemSucesso($"O registro ID [{aluguel.Id}] foi Finalizado com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    public IActionResult Excluir(int id)
    {
        var resultado = _aluguelService.SelecionarId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var aluguel = resultado.Value;

        var excluirVm = _mapeador.Map<ExcluirAluguelViewModel>(aluguel);

        return View(excluirVm);
    }

    [HttpPost]
    public IActionResult Excluir(ExcluirAluguelViewModel excluirVm)
    {
        var resultado = _aluguelService.Excluir(excluirVm.Id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"O registro foi deletado com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    private FormAluguelViewModel? CarregarDados(FormAluguelViewModel? model = null)
    {
        var resultadoGrupos = _grupoVeiculosService.SelecionarTodos(EmpresaId.GetValueOrDefault());
        var resultadoVeiculos = _veiculoService.SelecionarTodos(EmpresaId.GetValueOrDefault());
        var resultadoCondutores = _condutorService.SelecionarTodos(EmpresaId.GetValueOrDefault());
        var resultadoClientes = _clienteService.SelecionarTodos(EmpresaId.GetValueOrDefault());
        var resultadoPlanos = _planoService.SelecionarTodos(EmpresaId.GetValueOrDefault());
        var resultadoTaxas = _taxasService.SelecionarTodos(EmpresaId.GetValueOrDefault());


        if (resultadoClientes.IsFailed)
        {
            ApresentarMensagemFalha(resultadoClientes.ToResult());
            return null;
        }

        if (resultadoGrupos.IsFailed)
        {
            ApresentarMensagemFalha(resultadoGrupos.ToResult());
            return null;
        }

        if (resultadoCondutores.IsFailed)
        {
            ApresentarMensagemFalha(resultadoCondutores.ToResult());
            return null;
        }

        if (resultadoPlanos.IsFailed)
        {
            ApresentarMensagemFalha(resultadoPlanos.ToResult());
            return null;
        }
        if (resultadoVeiculos.IsFailed)
        {
            ApresentarMensagemFalha(resultadoVeiculos.ToResult());
            return null;
        }
        if (resultadoTaxas.IsFailed)
        {
            ApresentarMensagemFalha(resultadoTaxas.ToResult());
            return null;
        }
        var taxasD = resultadoTaxas.Value;
        var gruposD = resultadoGrupos.Value;
        var planosD = resultadoPlanos.Value;
        var clientesD = resultadoClientes.Value;
        var veiculosD = resultadoVeiculos.Value;
        var condutoresD = resultadoCondutores.Value;

        model ??= new CadastroAluguelViewModel
        {
            Taxas = taxasD,
            Clientes = clientesD.Select(x => new SelectListItem(x.Nome, x.Id.ToString())),
            Grupos = gruposD.Select(x => new SelectListItem(x.Nome, x.Id.ToString())),
            Veiculos = veiculosD.Select(x => new SelectListItem(x.Modelo, x.Id.ToString())),
            Condutores = condutoresD.Select(x => new SelectListItem(x.Nome, x.Id.ToString())),
            Planos = planosD.Select(x => new SelectListItem(x.TipoPlano.ToString(), x.Id.ToString()))
        };

        return model;
    }

    [HttpGet]
    public JsonResult CarregarCondutores(int clienteId)
    {
        var resultado = _condutorService.SelecionarTodos(EmpresaId.GetValueOrDefault());

        if (resultado.IsFailed)
        {
            return Json(new List<SelectListItem>());
        }

        var condutores = resultado.Value
            .Where(c => c.ClienteId == clienteId)
            .Select(c => new SelectListItem
            {

LocadoraDeVeiculos.WebApp/Views/Aluguel/Cadastrar.cshtml
@model CadastroAluguelViewModel
@{
    ViewBag.Title = "Cadastro de aluguel";
}
<div class="row d-flex justify-content-center">
    <div class="col-lg-6 ">
        <form asp-action="Cadastrar">
            <div class="form-group">
                <label asp-for="ClienteId" class="control-label">Cliente:</label>
                <select asp-for="ClienteId" class="form-control" asp-items="Model.Clientes" id="clienteSelect">
                    <option value="" disabled selected>Selecione um Cliente</option>
                </select>
                <span asp-validation-for="ClienteId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CondutorId" class="control-label">Condutor:</label>
                <select asp-for="CondutorId" class="form-control" id="condutorSelect" disabled>
                    <option value="" disabled selected>Selecione um Cliente</option>
                </select>
                <span asp-validation-for="CondutorId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="GrupoId" class="control-label">Grupo de Automóveis:</label>
                <select asp-for="GrupoId" class="form-control" asp-items="Model.Grupos" id="grupoSelect">
                    <option value="" disabled selected>Selecione um Grupo Veículo</option>
                </select>
                <span asp-validation-for="GrupoId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="VeiculoId" class="control-label">Automóvel:</label>
                <select asp-for="VeiculoId" class="form-control" asp-items="Model.Veiculos" id="veiculoSelect" disabled>
                    <option value="" disabled selected>Selecione um Grupo de Veículos</option>

                </select>
                <span asp-validation-for="VeiculoId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="DataLocacao" class="control-label">Data de Saída:</label>
                <input asp-for="DataLocacao" class="form-control" type="date" />
                <span asp-validation-for="DataLocacao" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="DateDevolucaoPrevista" class="control-label">Retorno:</label>
                <input asp-for="DateDevolucaoPrevista" class="form-control" type="date" />
                <span asp-validation-for="DateDevolucaoPrevista" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Entrada" class="control-label">Valor de Entrada:</label>
                <input asp-for="Entrada" value="1000" class="form-control" type="text" disabled />
                <span asp-validation-for="Entrada" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PlanoId" class="control-label">Plano:</label>
                <select asp-for="PlanoId" class="form-control" asp-items="Model.Planos" id="planoSelect" disabled>
                    <option value="" disabled selected>Selecione um Grupo de Veículos</option>
                </select>
                <span asp-validation-for="PlanoId" class="text-danger"></span>

                <partial name="_ListaDeTaxas" model="Model"/>

                <div class="form-group my-3">
                    <button type="submit" class="btn btn-primary">Cadastrar</button>
                    <a asp-action="Listar" class="btn btn-secondary">Cancelar</a>
                </div>
        </form>
    </div>
</div>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        $(function () {
            $('#clienteSelect').change(function () {
                var clienteId = $(this).val();
                var $condutorSelect = $('#condutorSelect');

                if (clienteId) {
                    $.get('@Url.Action("CarregarCondutores", "Aluguel")', { clienteId: clienteId }, function (data) {
                        $condutorSelect.empty().append('<option value="" disabled selected>Selecione</option>');
                        $.each(data, function (_, condutor) {
                            $condutorSelect.append($('<option>', { value: condutor.value, text: condutor.text }));
                        });
                        $condutorSelect.prop('disabled', false);
                    });
                } else {
                    $condutorSelect.empty().append('<option value="" disabled selected>Selecione</option>').prop('disabled', true);
                }
            });

            $('#grupoSelect').change(function () {
                var grupoId = $(this).val();
                var $veiculoSelect = $('#veiculoSelect');

                if (grupoId) {
                    $.get('@Url.Action("CarregarVeiculos", "Aluguel")', { grupoId: grupoId }, function (data) {
                        $veiculoSelect.empty().append('<option value="">Selecione</option>');
                        $.each(data, function (_, veiculo) {
                            $veiculoSelect.append($('<option>', { value: veiculo.value, text: veiculo.text }));
                        });
                        $veiculoSelect.prop('disabled', false);
                    });
                } else {
                    $veiculoSelect.empty().append('<option value="">Selecione</option>').prop('disabled', true);
                }
            });

            $('#grupoSelect').change(function () {
                var grupoId = $(this).val();
                var $planoSelect = $('#planoSelect');

                if (grupoId) {
                    $.get('@Url.Action("CarregarPlanos", "Aluguel")', { grupoId: grupoId }, function (data) {
                        $planoSelect.empty().append('<option value="">Selecione</option>');
                        $.each(data, function (_, plano) {
                            $planoSelect.append($('<option>', { value: plano.value, text: plano.text }));
                        });
                        $planoSelect.prop('disabled', false);
                    });
                } else {
                    $planoSelect.empty().append('<option value="">Selecione</option>').prop('disabled', true);
                }
            });
        });
    </script>
}

LocadoraDeVeiculos.WebApp/Views/Aluguel/Detalhes.cshtml
@model DetalhesAluguelViewModel
@{
    ViewBag.Title = "Detalhes do Aluguel";
}
<hr />
<div class="row d-flex justify-content-center">
    <div class="col-lg-6 ">
        <div class="form-group">
            <label>Cliente:</label>
            <input class="form-control" value="@Model.Cliente.Nome" disabled />
        </div>
        <div class="form-group">
            <label>Condutor:</label>
            <input class="form-control" value="@Model.Condutor.Nome" disabled />
        </div>
        <div class="form-group">
            <label>Grupo de Veículos:</label>
            <input class="form-control" value="@Model.Grupo.Nome" disabled />
        </div>

        <div class="form-group">
            <label>Veículo:</label>
            <input class="form-control" value="@Model.Veiculo.Modelo" disabled />
        </div>

        <div class="form-group">
            <label>Plano:</label>
            <input class="form-control" value="@Model.Plano.TipoPlano.ToString()" disabled />
        </div>

        <div class="form-group">
            <label>Data de Locação:</label>
            <input class="form-control" value="@Model.DataLocacao.ToString("dd/MM/yyyy")" disabled />
        </div>

        <div class="form-group">
            <label>Data de Devolução Prevista:</label>
            <input class="form-control" value="@Model.DateDevolucaoPrevista.Value.ToString("dd/MM/yyyy")" disabled />
        </div>

        <div class="form-group">
            <label>Valor de Entrada:</label>
            <input class="form-control" value="@Model.Entrada.ToString("C")" disabled />
        </div>

        <div class="form-group">
            <label>Taxas:</label>
            @if (Model.Taxas is not null)
            {
                <ul class="list-group">
                    @foreach (var taxa in Model.Taxas)
                    {
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            @taxa.Nome - @taxa.Valor.ToString("C")

                        </li>
                    }
                </ul>
            }
            else
            {
                <p class="form-control-static">Nenhuma taxa aplicada.</p>
            }
        </div>
        <div class="form-group my-3">
            <a asp-action="Listar" class="btn btn-secondary">Voltar</a>
        </div>
    </div>
</div>

LocadoraDeVeiculos.WebApp/Views/Aluguel/Editar.cshtml
@model EditarAluguelViewModel

@{
    ViewBag.Title = "Editar Aluguel";
}
<hr />
<div class="row d-flex justify-content-center">
    <div class="col-lg-6 ">
        <form asp-action="Editar" method="post">
            <div class="form-group">
                <label asp-for="ClienteId" class="control-label">Cliente:</label>
                <select asp-for="ClienteId" class="form-control" asp-items="@Model.Clientes" id="clienteSelect" disabled>
                    <option value="" disabled>Selecione um Cliente</option>
                </select>
                <span asp-validation-for="ClienteId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CondutorId" class="control-label">Condutor:</label>
                <select asp-for="CondutorId" class="form-control" id="condutorSelect">
                    <option value="" disabled>Selecione um Condutor</option>
                </select>
                <span asp-validation-for="CondutorId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="GrupoId" class="control-label">Grupo de Automóveis:</label>
                <select asp-for="GrupoId" class="form-control" asp-items="Model.Grupos" id="grupoSelect">
                    <option value="" disabled>Selecione um Grupo Veículo</option>
                </select>
                <span asp-validation-for="GrupoId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="VeiculoId" class="control-label">Automóvel:</label>
                <select asp-for="VeiculoId" class="form-control" asp-items="Model.Veiculos" id="veiculoSelect">
                    <option value="" disabled>Selecione um Veículo</option>
                </select>
                <span asp-validation-for="VeiculoId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="DataLocacao" class="control-label">Data de Saída:</label>
                <input asp-for="DataLocacao" class="form-control" type="date" disabled />
                <span asp-validation-for="DataLocacao" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="DateDevolucaoPrevista" class="control-label">Retorno:</label>
                <input asp-for="DateDevolucaoPrevista" class="form-control" type="date" />
                <span asp-validation-for="DateDevolucaoPrevista" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Entrada" class="control-label">Valor de Entrada:</label>
                <input asp-for="Entrada" class="form-control" type="text" />
                <span asp-validation-for="Entrada" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PlanoId" class="control-label">Plano:</label>
                <select asp-for="PlanoId" class="form-control" asp-items="Model.Planos" id="planoSelect">
                    <option value="" disabled>Selecione um Plano</option>
                </select>
                <span asp-validation-for="PlanoId" class="text-danger"></span>
            </div>

            <partial name="_ListaDeTaxas" model="Model" />

            <div class="form-group">
                <label>Taxas:</label>
                @if (Model.Taxas is not null)
                {
                    <ul class="list-group">
                        @foreach (var taxa in Model.Taxas)
                        {
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                @taxa.Nome - @taxa.Valor.ToString("C")

                            </li>
                        }
                    </ul>
                }
                else
                {
                    <p class="form-control-static">Nenhuma taxa aplicada.</p>
                }
            </div>


            <div class="form-group my-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
                <a asp-action="Listar" class="btn btn-secondary">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        $(function () {
            $('#clienteSelect').change(function () {
                var clienteId = $(this).val();
                var $condutorSelect = $('#condutorSelect');

                if (clienteId) {
                    $.get('@Url.Action("CarregarCondutores", "Aluguel")', { clienteId: clienteId }, function (data) {
                        $condutorSelect.empty().append('<option value="" disabled>Selecione</option>');
                        $.each(data, function (_, condutor) {
                            $condutorSelect.append($('<option>', { value: condutor.value, text: condutor.text }));
                        });
                        $condutorSelect.prop('disabled', false);

                        $condutorSelect.val('@Model.CondutorId');
                    });
                } else {
                    $condutorSelect.empty().append('<option value="" disabled>Selecione</option>').prop('disabled', true);
                }
            });

            $('#grupoSelect').change(function () {
                var grupoId = $(this).val();
                var $veiculoSelect = $('#veiculoSelect');

                if (grupoId) {
                    $.get('@Url.Action("CarregarVeiculos", "Aluguel")', { grupoId: grupoId }, function (data) {
                        $veiculoSelect.empty().append('<option value="" disabled>Selecione</option>');
                        $.each(data, function (_, veiculo) {
                            $veiculoSelect.append($('<option>', { value: veiculo.value, text: veiculo.text }));
                        });
                        $veiculoSelect.prop('disabled', false);

                        $veiculoSelect.val('@Model.VeiculoId');
                    });
                } else {
                    $veiculoSelect.empty().append('<option value="" disabled>Selecione</option>').prop('disabled', true);
                }
            });

            $('#grupoSelect').change(function () {
                var grupoId = $(this).val();
                var $planoSelect = $('#planoSelect');

                if (grupoId) {
                    $.get('@Url.Action("CarregarPlanos", "Aluguel")', { grupoId: grupoId }, function (data) {
                        $planoSelect.empty().append('<option value="" disabled>Selecione</option>');
                        $.each(data, function (_, plano) {
                            $planoSelect.append($('<option>', { value: plano.value, text: plano.text }));
                        });
                        $planoSelect.prop('disabled', false);

                        $planoSelect.val('@Model.PlanoId');
                    });
                } else {
                    $planoSelect.empty().append('<option value="" disabled>Selecione</option>').prop('disabled', true);
                }
            });

            $(document).ready(function () {
                $('#clienteSelect').val('@Model.ClienteId').change();

                $('#grupoSelect').val('@Model.GrupoId').change();
            });
        });
    </script>
}