LocadoraDeVeiculos.WebApp/Models/MensagemViewModel.cs
namespace LocadoraDeVeiculos.WebApp.Models;

public class MensagemViewModel
{
    public string Titulo { get; set; }
    public string Mensagem { get; set; }
}

LocadoraDeVeiculos.WebApp/Controllers/AuthController.cs
using LocadoraDeVeiculos.Aplicacao.Services;
using LocadoraDeVeiculos.Dominio.ModuloAuth;
using LocadoraDeVeiculos.Dominio.ModuloUsuario;
using LocadoraDeVeiculos.WebApp.Controllers.Shared;
using LocadoraDeVeiculos.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace LocadoraDeVeiculos.WebApp.Controllers;
public class AuthController : WebController
{
    readonly AuthService _authService;
    public AuthController(AuthService authService) : base(authService)
    {
        _authService = authService;
    }

    public IActionResult Registrar()
    {
        return View(new RegistrarEmpresaViewModel());
    }

    [HttpPost]
    public async Task<IActionResult> Registrar(RegistrarEmpresaViewModel registrarVm)
    {
        if (!ModelState.IsValid)
            return View(registrarVm);

        var usuario = new Usuario()
        {
            UserName = registrarVm.Usuario,
            Email = registrarVm.Email
        };

        var senha = registrarVm.Senha!;

        var resultado = await _authService
            .Registrar(usuario, senha, TipoUsuarioEnum.Empresa);

        if (resultado.IsSuccess)
            return RedirectToAction("Index", "Home");

        foreach (var erro in resultado.Errors)
            ModelState.AddModelError(string.Empty, erro.Message);

        return View(registrarVm);
    }

    public IActionResult Login(string? returnUrl = null)
    {
        ViewBag.ReturnUrl = returnUrl;

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Login(LoginEmpresaViewModel loginVm, string? returnUrl = null)
    {
        ViewBag.ReturnUrl = returnUrl;

        if (!ModelState.IsValid)
            return View(loginVm);

        var resultado = await _authService.Login(loginVm.Usuario!, loginVm.Senha!);

        if (resultado.IsSuccess)
            return LocalRedirect(returnUrl ?? "/");

        var msgErro = resultado.Errors.First().Message;

        ModelState.AddModelError(string.Empty, msgErro);

        return View(loginVm);
    }

    [HttpPost]
    public async Task<IActionResult> Logout()
    {
        await _authService.Logout();

        return RedirectToAction(nameof(Login));
    }

    public IActionResult AcessoNegado()
    {
        return View();
    }
}

LocadoraDeVeiculos.WebApp/Controllers/ClienteController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using LocadoraDeVeiculos.Dominio;
using LocadoraDeVeiculos.WebApp.Models;
using LocadoraDeVeiculos.WebApp.Extensions;
using LocadoraDeVeiculos.Aplicacao.Services;
using FluentResults;
using LocadoraDeVeiculos.WebApp.Controllers.Shared;

namespace LocadoraDeVeiculos.WebApp.Controllers;
public class ClienteController : WebController
{
    readonly IMapper _mapeador;
    readonly ClienteService _serviceCliente;

    public ClienteController(IMapper mapeador, ClienteService serviceCliente,
        AuthService authService) : base(authService)
    {
        _mapeador = mapeador;
        _serviceCliente = serviceCliente;
    }

    public IActionResult Listar()
    {
        var resultado = _serviceCliente.SelecionarTodos(EmpresaId.GetValueOrDefault());

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return View("Index", "Home");
        }

        var clientes = resultado.Value;

        var listarVm = _mapeador.Map<IEnumerable<ListarClienteViewModel>>(clientes);

        ViewBag.Mensagem = TempData.DesserializarMensagemViewModel();

        return View(listarVm);
    }

    public ActionResult Detalhes(int id)
    {
        var resultado = _serviceCliente.SelecionarId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult()); ////Ainda não implementado

            return RedirectToAction(nameof(Listar));
        }

        var cliente = resultado.Value;

        var detalhesVm = _mapeador.Map<FormClienteViewModel>(cliente);

        return View(detalhesVm);
    }

    public ActionResult Cadastrar()
    {
        return View();
    }

    [HttpPost]
    public ActionResult Cadastrar(FormClienteViewModel cadastroVm)
    {
        if (!ModelState.IsValid)
            return View(cadastroVm);

        var cliente = _mapeador.Map<Cliente>(cadastroVm);

        var resultado = _serviceCliente.Cadastrar(cliente);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"O registro ID [{cliente.Id}] foi cadastrado com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    public ActionResult Editar(int id)
    {
        var resultado = _serviceCliente.SelecionarId(id);

        if(resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var cliente = resultado.Value;

        var editarVm = _mapeador.Map<FormClienteViewModel>(cliente);

        return View(editarVm);
    }

    [HttpPost]
    public ActionResult Editar(FormClienteViewModel editarVm)
    {
        if (!ModelState.IsValid)
            return View(editarVm);

        var cliente = _mapeador.Map<Cliente>(editarVm);

        var resultado = _serviceCliente.Editar(cliente);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult()); ////Ainda não implementado

            return RedirectToAction(nameof(Editar));
        }

        ApresentarMensagemSucesso($"O registro ID [{cliente.Id}] foi editado com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    public ActionResult Excluir(int id)
    {
        var resultado = _serviceCliente.SelecionarId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult()); ////Ainda não implementado

            return RedirectToAction(nameof(Listar));
        }

        var cliente = resultado.Value;

        var detalhesVm = _mapeador.Map<FormClienteViewModel>(cliente);

        return View(detalhesVm);
    }

    [HttpPost]
    public ActionResult Excluir(FormClienteViewModel excluirVm)
    {
        var resultado = _serviceCliente.Excluir(excluirVm.Id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult()); ////Ainda não implementado

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"O registro foi deletado com sucesso!");

        return RedirectToAction(nameof(Listar));
    }
}

LocadoraDeVeiculos.WebApp/Controllers/PlanoController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using LocadoraDeVeiculos.Dominio;
using LocadoraDeVeiculos.WebApp.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using LocadoraDeVeiculos.WebApp.Extensions;
using LocadoraDeVeiculos.Aplicacao.Services;
using LocadoraDeVeiculos.WebApp.Controllers.Shared;

namespace LocadoraDeVeiculos.WebApp.Controllers;
public class PlanoController : WebController
{
    readonly IMapper _mapeador;
    readonly PlanoService _servicePlano;
    readonly GrupoVeiculosService _serviceGrupo;

    public PlanoController(
        IMapper mapeador,
        PlanoService servicePlano,
        GrupoVeiculosService serviceGrupo,
        AuthService authService) : base(authService)
    {
        _mapeador = mapeador;
        _servicePlano = servicePlano;
        _serviceGrupo = serviceGrupo;
    }

    public IActionResult Listar()
    {
        var resultado = _servicePlano.SelecionarTodos(EmpresaId.GetValueOrDefault());

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return View("Index", "Home");
        }

        var planos = resultado.Value;

        var listarVm = _mapeador.Map<IEnumerable<ListarPlanoViewModel>>(planos);

        ViewBag.Mensagem = TempData.DesserializarMensagemViewModel();

        return View(listarVm);
    }

    public IActionResult Detalhes(int id)
    {
        var resultado = _servicePlano.SelecionarId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var plano = resultado.Value;

        var detalhesVm = _mapeador.Map<FormPlanoViewModels>(plano);

        return View(detalhesVm);
    }

    public IActionResult Cadastrar()
    {
        return View(CarregarDadosFormulario());
    }

    [HttpPost]
    public IActionResult Cadastrar(FormPlanoViewModels cadastroVm)
    {
        VerificarValidacaoDeModelo(cadastroVm);

        if (!ModelState.IsValid)
            return View(CarregarDadosFormulario(cadastroVm));

        var plano = _mapeador.Map<Plano>(cadastroVm);

        var resultado = _servicePlano.Cadastrar(plano);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult()); 

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"O registro ID [{plano.Id}] foi cadastrado com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    private void VerificarValidacaoDeModelo(FormPlanoViewModels cadastroVm)
    {
        if (cadastroVm.TipoPlano == TipoPlano.Diario)
        {
            ModelState.Remove("ValorExtrapolado");
            ModelState.Remove("kmDisponivel");
        }
        else
        {
            ModelState.Remove("PrecoKm");
            ModelState.Remove("ValorExtrapolado");
            ModelState.Remove("kmDisponivel");
        }
    }

    public IActionResult Editar(int id)
    {
        var resultado = _servicePlano.SelecionarId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult()); 

            return RedirectToAction(nameof(Listar));
        }

        var resultadoGrupos = _serviceGrupo.SelecionarTodos(EmpresaId.GetValueOrDefault());

        if (resultadoGrupos.IsFailed)
        {
            ApresentarMensagemFalha(resultadoGrupos.ToResult());

            return null;
        }

        var plano = resultado.Value;

        var editarVm = _mapeador.Map<FormPlanoViewModels>(plano);

        var gruposDisponiveis = resultadoGrupos.Value;

        editarVm.GrupoVeiculos = gruposDisponiveis
            .Select(g => new SelectListItem
            {
                Value = g.Id.ToString(),
                Text = g.Nome,
                Selected = g.Id == plano.GrupoVeiculos.Id 
            }).ToList();

        return View(editarVm);
    }

    [HttpPost]
    public IActionResult Editar(int id, FormPlanoViewModels editarVm)
    {
        VerificarValidacaoDeModelo(editarVm);

        if (!ModelState.IsValid)
            return View(CarregarDadosFormulario(editarVm));

        var plano = _mapeador.Map<Plano>(editarVm);

        var resultado = _servicePlano.Editar(plano);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Editar));
        }

        ApresentarMensagemSucesso($"O registro ID [{plano.Id}] foi editado com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    public IActionResult Excluir(int id)
    {
        var resultado = _servicePlano.SelecionarId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var plano = resultado.Value;

        var excluirVm = _mapeador.Map<FormPlanoViewModels>(plano);

        return View(excluirVm);
    }

    [HttpPost]
    public IActionResult Excluir(FormPlanoViewModels excluirVm)
    {
        var resultado = _servicePlano.Excluir(excluirVm.Id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"O registro foi deletado com sucesso!");

        return RedirectToAction(nameof(Listar));
    }
    private FormPlanoViewModels? CarregarDadosFormulario(
       FormPlanoViewModels? dadosPrevios = null)
    {
        var resultadoGrupos = _serviceGrupo.SelecionarTodos(EmpresaId.GetValueOrDefault());

        if (resultadoGrupos.IsFailed)
        {
            ApresentarMensagemFalha(resultadoGrupos.ToResult());
            return null;
        }

        var gruposDisponiveis = resultadoGrupos.Value;

        if (dadosPrevios is null)
        {
            var formularioVm = new FormPlanoViewModels
            {
                GrupoVeiculos = gruposDisponiveis.Select(g => new SelectListItem(g.Nome, g.Id.ToString()))
            };
            return formularioVm;
        }

        dadosPrevios.GrupoVeiculos = gruposDisponiveis.Select(g => new SelectListItem(g.Nome, g.Id.ToString()));
        return dadosPrevios;
    }
}

LocadoraDeVeiculos.WebApp/Controllers/TaxasController.cs
using AutoMapper;
using FluentResults;
using LocadoraDeVeiculos.Aplicacao.Services;
using LocadoraDeVeiculos.Dominio.ModuloAlugueis.ModuloTaxas;
using LocadoraDeVeiculos.Dominio.ModuloVeiculos;
using LocadoraDeVeiculos.WebApp.Controllers.Shared;
using LocadoraDeVeiculos.WebApp.Extensions;
using LocadoraDeVeiculos.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;

namespace LocadoraDeVeiculos.WebApp.Controllers;
public class TaxasController : WebController
{
    readonly IMapper _mapeador;
    readonly TaxasService _serviceTaxas;

    public TaxasController(
        IMapper mapeador,
        TaxasService serviceTaxas,
        AuthService authService) : base(authService)
    {
        _mapeador = mapeador;
        _serviceTaxas = serviceTaxas;
    }

    public IActionResult Listar()
    {
        var resultado = _serviceTaxas.SelecionarTodos(EmpresaId.GetValueOrDefault());

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction("Index", "Home");
        }

        var taxas = resultado.Value;

        var listarVm = _mapeador.Map<IEnumerable<ListarTaxasViewModel>>(taxas);

        ViewBag.Mensagem = TempData.DesserializarMensagemViewModel();

        return View(listarVm);
    }

    public IActionResult Detalhes(int id)
    {
        var resultado = _serviceTaxas.SelecionarId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var taxas = resultado.Value;

        var editarVm = _mapeador.Map<FormTaxasViewModel>(taxas);

        return View(editarVm);
    }

    public IActionResult Cadastrar()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Cadastrar(FormTaxasViewModel cadastroVm)
    {
        if (!ModelState.IsValid)
            return View(cadastroVm);

        var taxa = _mapeador.Map<TaxaServico>(cadastroVm);

        var resultado = _serviceTaxas.Cadastrar(taxa);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"O registro ID [{taxa.Id}] foi cadastrado com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    public IActionResult Editar(int id)
    {
        var resultado = _serviceTaxas.SelecionarId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var taxa = resultado.Value;

        var editarVm = _mapeador.Map<FormTaxasViewModel>(taxa);

        return View(editarVm);
    }

    [HttpPost]
    public IActionResult Editar(FormTaxasViewModel editarVm)
    {
        var taxa = _mapeador.Map<TaxaServico>(editarVm);

        var resultado = _serviceTaxas.Editar(taxa);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"O registro ID [{taxa.Id}] foi editado com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    public IActionResult Excluir(int id)
    {
        var resultado = _serviceTaxas.SelecionarId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var taxa = resultado.Value;

        var excluirVM = _mapeador.Map<FormTaxasViewModel>(taxa);

        return View(excluirVM);
    }

    [HttpPost]
    public IActionResult Excluir(FormTaxasViewModel excluirVm)
    {


        var resultado = _serviceTaxas.Excluir(excluirVm.Id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"O registro foi deletado com sucesso!");

        return RedirectToAction(nameof(Listar));
    }
}

LocadoraDeVeiculos.WebApp/Views/Shared/_Layout.cshtml
@{
    MensagemViewModel? mensagem = ViewBag.Mensagem ?? null;
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - Locadora De Veiculos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LocadoraDeVeiculos.WebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
</head>
<body style="height:auto; margin-bottom: 7rem;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid mx-lg-5">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Locadora De Veiculos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-end fs-5">
                        @if (User.Identity is not null && User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Veiculo" asp-action="Listar">Veiculos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="GrupoVeiculos" asp-action="Listar">Grupos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Plano" asp-action="Listar">Planos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Listar">Clientes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Condutor" asp-action="Listar">Condutores</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Taxas" asp-action="Listar">Taxas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Aluguel" asp-action="Listar">Alugueis</a>
                            </li>

                            <div class="dropdown">

                                <button class="btn btn-outline-primary dropdown-toggle mx-3 px-3 d-flex flex-nowrap align-items-center" type="button" id="dropMenu" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-person-vcard-fill px-2"></i>
                                    @User.Identity.Name
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropMenu">

                                    <li>
                                        <button class="dropdown-item d-flex flex-nowrap align-items-center" type="button">
                                            <i class="bi bi-person-square"></i>
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Funcionario" asp-action="Listar">Funcionario</a>
                                        </button>
                                    </li>

                                    <li>
                                        <button class="dropdown-item d-flex flex-nowrap align-items-center" type="button">
                                            <i class="bi bi-fuel-pump"></i>
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Combustivel" asp-action="Configuracao">Combustível</a>
                                        </button>
                                    </li>
                                </ul>
                            </div>

                            <form asp-controller="Auth" asp-action="Logout">
                                <button class="btn btn-secondary px-3">
                                    <i class="bi bi-box-arrow-right"></i>
                                    Logout
                                </button>
                            </form>
                        }
                        else
                        {
                            <div class="d-flex flex-lg-nowrap">
                                <a asp-controller="Auth" asp-action="Login" class="btn btn-outline-primary me-2 px-4">Login</a>
                                <a asp-controller="Auth" asp-action="Registrar" class="btn btn-outline-primary px-4">Registro</a>
                            </div>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <h1 class="text-light-emphasis">@ViewBag.Title</h1>
        <hr />
        <main role="main" class="pb-3">
            <partial name="_Mensagem" model="mensagem"></partial>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container d-flex justify-content-center align-content-center">
            &copy; 2024 - Locadora De Veiculos 2024 - Desenvolvido por
            <a href="https://github.com/Kriegerl1"
               style="text-decoration:none;accent-color:black; font-weight:700; color:#8B0000;margin-inline-start: .5rem">
            Leo Rodrigues</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LocadoraDeVeiculos.WebApp/Views/Shared/_Mensagem.cshtml
@model MensagemViewModel?

@if (Model is not null)
{
    var corAlerta = Model.Titulo == "Sucesso" ? "alert-success" : "alert-danger";
    var iconeSelecionado = Model.Titulo == "Sucesso" ? "bi-check-circle-fill" : "bi-info-circle-fill";

    <div class="alert @corAlerta alert-dismissible fade show" role="alert">
        <i class="bi @iconeSelecionado"></i>
        <strong>@Model.Titulo:</strong> @Model.Mensagem
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}